version: "3.3"
services:
 ansible_amd64:
  build:
   context: .
   dockerfile: Dockerfile_x86
  platform: linux/x86_64
  tty: true
  ports:
    - "2222:22"
    - "8080:80"
  volumes:
   - ./01_Apache_laravel:/home/ec2-user/apache_laravel
  working_dir: /home/ec2-user/
  privileged: true
  restart: always
  command: /sbin/init
