- name: Enable to install PHP.
  shell: "amazon-linux-extras enable php7.4"
  changed_when: False

- name: yum php install
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: amzn2extra-php7.4
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-pecl-zip
    - php-pdo
    - php-xml
    - php-fpm
    - php-gd

- name: index php
  template:
    src: ../templates/index.php.j2
    dest: /var/www/html/index.php
